### ISSUE TITLE
About page is not showing up

### ISSUE THREAD

**Issue by diana-pilvar** [elixir-uk/elixir-ds-handbook#11]
https://github.com/elixir-uk/elixir-ds-handbook/blob/main/pages/about/about.md this is not visible on homepage

 https://elixir-uk.github.io/elixir-ds-handbook/about and instead there is fellowship text still

**Comment by Nazeeefa** [comment]
@bedroesb let me know when/how this is fixed, curious to what solved it 😄 as far as I understand, we may need to check SCSS files to make sure numbers and strings are properly defined, and that sorting logic is correctly included (though I am unsure what it is needed/used for, for this site).

**Comment by sitjart** [comment]
Fixed now. It was the contributors list on a page. It was listed without [, ]

**Comment by bedroesb** [comment]
And `layout: none` did also not help ;)
